name: AWS Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/party-user-backend
            git pull origin main
            npm install --production
            pm2 restart user-backend
            echo "🚀 User Backend Deployment successful!"
